version: '2.4'

services:

  gen-req:
    image: brsynth/pip-gen-req
    build:
      context: ..
      dockerfile: docker/req.dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
    command: sh -c 'pip-compile requirements.in > requirements.txt'
    volumes:
      - ../requirements:/req

  install:
    image: brsynth/${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
    command: python3.8 rpCache/rpCache.py -sm db
    networks:
      - db
    depends_on:
      - db
    volumes:
      - input_cache:/home/input_cache
      - cache:/home/cache

  clean-cache:
    image: busybox
    command: sh -c "rm -f /cache/*"
    volumes:
      - cache:/cache
    network_mode: "none"

  clean-input-cache:
    image: busybox
    command: sh -c "rm -f /input_cache/*"
    volumes:
      - input_cache:/input_cache
    network_mode: "none"

  db:
    image: redis:5-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    networks:
      db:
    volumes:
      - redis:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    mem_limit: 1024m

  backup:
    image: alpine
    volumes:
      - input_cache:/input_cache:ro
      - cache:/cache:ro
      - $PWD/backup:/backup
    entrypoint: sh -c "
                  tar -czf /backup/input_cache.tgz /input_cache
               && tar -czf /backup/cache.tgz /cache
                  "
    network_mode: "none"

  restore:
    image: alpine
    volumes:
      - input_cache:/input_cache
      - cache:/cache
      - $PWD/backup:/backup:ro
    entrypoint: sh -c "
                  tar -xzf /backup/input_cache.tgz -C /
               && tar -xzf /backup/cache.tgz -C /
                  "
    network_mode: "none"

volumes:
  input_cache:
  cache:
  redis:

networks:
  db:
